apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook.name" . }}
    chart: {{ include "webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    watcher.ibm.com/opt-in: {{ .Values.watcher.optIn | quote }}
  annotations:
    watcher.ibm.com/configmap-resource: "{{ .Values.watcher.configmap.namespace }}/{{ .Values.watcher.configmap.name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "webhook.name" . }}
      release: {{ .Release.Name }}
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        k8s-app: "cert-manager-webhook"
        chart: {{ template "webhook.chart" . }}
        heritage: {{ .Release.Service }}
        app: {{ include "webhook.name" . }}
        release: {{ .Release.Name }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "webhook.serviceAccountName" . }}
      {{- if .Values.global.priorityClassName }}
      priorityClassName: {{ .Values.global.priorityClassName | quote }}
      {{- end }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.pod.runAsNonRoot }}
{{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }} 
        runAsUser: {{ .Values.securityContext.pod.runAsUser }}
{{- end }}          
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --v={{ .Values.args.verbosity }}
          - --secure-port=1443
          - --tls-cert-file=/certs/tls.crt
          - --tls-private-key-file=/certs/tls.key
        {{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 10 }}
        {{- end }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TMPDIR
            value: "/home/webhook/tmp"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - pgrep webhook -l
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "exec echo start cert-manager webhook"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: {{ .Values.securityContext.container.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.container.readOnlyRootFilesystem }}
            capabilities:
              drop:
              - ALL
{{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }} 
            runAsUser: {{ .Values.securityContext.container.runAsUser }}
{{- end }}              
            runAsNonRoot: {{ .Values.securityContext.container.runAsNonRoot }}
          volumeMounts:
          - name: certs
            mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: {{ include "webhook.servingCertificate" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
